name: Recent GitHub Activity

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          RA_GITHUB_TOKEN: ${{ secrets.RA_GITHUB_TOKEN }}
