name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * 0"  # every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-cards

    steps:
      - uses: actions/checkout@v2

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Savvythelegend
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Use a custom PAT
